@BlukOperationDapper_HostAddress = https://localhost:7239

GET {{BlukOperationDapper_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BlukOperationDapper_HostAddress}}/api/person/bulk-person

###
